version: "3"

services:

  ss3:
    image: albertozuga/aos-ss3:1.0.1
    ports:
      - "8080:8080"
    networks:
      - ss3-net
    depends_on:
      ss3-db:
        condition: service_started

  ss3-db:
    image: mysql:8
    restart: always
    networks:
      - ss3-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobs
      - MYSQL_USER=jobservice
      - MYSQL_PASSWORD=jobservice
    volumes:
      - db_data:/var/lib/mysql


networks:

  ss3-net:

volumes:
  db_data: